### ISSUE TITLE
Remove // js and php comments

### ISSUE THREAD

**Issue by trompx** [anseki/grunt-htmlclean#3]
Hello,

Is there a way to allow htmlclean to remove // comments inside <?php ... ?> and inline javascript <script>... </script>?
That would be awesome.

Thank you for the plugin

**Comment by anseki** [comment]
Hi @trompx,

Since htmlclean protects those, you can add minifier for those to your task.
For example, following task minifies `INPUT.html` that contains inline JavaScript, and writes it to `OUTPUT.html`.

Install packages if you don't have.

```
npm install grunt-task-helper htmlclean uglify-js
```

```js
module.exports = grunt => {
  const htmlclean = require('htmlclean'),
    uglify = require('uglify-js');

  grunt.initConfig({
    taskHelper: {
      minHTML: {
        options: {
          handlerByContent: content => {
            return htmlclean(content.replace(/(<script\b[^>]*>)([\s\S]*?)(<\/script>)/gi,
              (s, open, code, close) => `${open}${code ? uglify.minify(code, {fromString: true}).code : ''}${close}`));
          }
        },
        src: 'INPUT.html',
        dest: 'OUTPUT.html'
      }
    }
  });

  grunt.loadNpmTasks('grunt-task-helper');
  grunt.registerTask('default', ['taskHelper:minHTML']);
};
```

CSS code also can be minified by this way with CSS minifier (e.g. clean-css).

**Comment by anseki** [comment]
No reply came, and I close this issue.
